[target.thumbv7em-none-eabihf]
runner = 'rocket-cli download STM32H743VIHx ../../Rust_Monorepo/secret.key void-lake'
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "linker=flip-link",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"

[unstable]
build-std = ["core"]
# Uncomment to get rid of all the panic messages, makes it a lot harder to debug but saves a lot of space
# build-std-features = ["panic_immediate_abort"]
